# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a465c91fe044647231f609b422294be509c09feb8136abba90669dff5275148cefe242e962014a39b05bff91111978d89adfccebb5214e5a155244d3c7633fe4

test:
  secret_key_base: e9a8145976e9b889c75620ffea1e5dea03463b76fa784ca7125f984a1ba247aa58c6ecad7d5ff13a82a2df3aff125bcea909665365ce9eae5c930865510fcca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
